version: '3.3'
volumes:
  db-data:
  redis-data:
  cassandra-data:
services:
  db:
    image: mysql:5.6
    ports:
    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=challenge
  cassandra:
    image: cassandra:latest
    ports:
    - "7000:7000"
    volumes:
    - cassandra-data:/var/lib/cassandra
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
    entrypoint: redis-server --appendonly yes
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
    - db
    - cassandra
    - redis
    ports:
    - 80:80
    environment:
    - PMA_ARBITRARY=1
