# Generated by Django 2.2.3 on 2019-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
